pycromanager/core.py

This PR replaces the usage of eval and exec for dynamic generation of methods to mirror java methods.
The reasoning for this is the `exec` and `eval` can cause a number of problems:
- IDE's don't recognize the code in exec statements so automatic refactoring can easily break them.
- Complex string formatting for the purpose of code generation is very difficult to read.
- Any code executed within an exec statement cannot be reached by a debugger.
Additional changes:
- `_parse_arg_names` no longer needlessly loops though all items of `methods_with_name` when only the last one is actually used.
- Generated methods now have type annotations for arguments and return values
- Generated methods now have generated docstrings.
For example here is the output from the built-in `help` function …

Replace usage of eval and exec

---

pycromanager/acquire.py

When using a relative path, it would make more sense to use the current working directory rather than the Micro-Manager installation folder. Futhermore, expending the user (~) would be nice.

Use CWD for relative paths

---

setup.py

The current homepage link on pypi links to what looks like the original repo before this joined the micro-manager org. This makes the canonical repo easier to find.
p.s. This is fantastic thank you so much

correct homepage url on pypi

---

pycromanager/data.py

`_tile_height` and `_tile_width` in `Dataset` are not garunteed to be defined, but they were still being used to reshape images which was leading to errors. Heres an example of how to reproduce the errors:
```python
from pycromanager import Bridge
from pycromanager import Acquisition, multi_d_acquisition_events
bridge = Bridge()
core = bridge.get_core()
mmStudio = bridge.get_studio()
z_pos = core.get_position()
z_delta = 3
z_start = z_pos - z_delta
z_end = z_pos + z_delta
z_step = 1
events = multi_d_acquisition_events(1,z_start= z_start, z_end = z_end,z_step=z_step, channel_group = 'UPLSAPO40X',channels=['BF', 'GFP'])
events = multi_d_acquisition_events(1,z_start= z_start, z_end = z_end,z_step=z_step,
channel_group = 'UPLSAPO40X',channels=['BF', 'GFP'])
with Acquisition(directory='test', …
```

add check for if tile_height and tile_width have been defined

---

docs/source/Stage-scanned light sheet imaging.ipynb
docs/source/convert MM MDA data into zarr.ipynb

two jupyter notebooks related with light sheet imaging:
1) convert MM MDA data into zarr. Using pycromanger as a reader to readout large MDA tiff files saved by micro-manager.
2) Stage-scanned light sheet imaging. A new scanning method in light sheet microscopy. 
For details of the method: https://www.biorxiv.org/content/10.1101/2020.09.22.309229v1

add two jupyter notebooks related with light sheet imaging

---

docs/source/conf.py
pycromanager/acquire.py
pycromanager/core.py
pycromanager/data.py
requirements.txt

As in the title. Switched to numpy style docstrings
Achieved through the use of https://github.com/dadadel/pyment and some elbow grease.
Closes: https://github.com/micro-manager/pycro-manager/issues/151
There were a few places where I inferred what the type should be, but a few where I wasn't confident and left them blank. Some of private functions also picked up docstrings by the action of `pyment` but I figure this isn't removing information so it's not the end of the world. Happy to remove if you'd prefer.

switch to numpydoc style docstrings

---

.github/workflows/test.yml
.gitignore
docs/source/acq_events.rst
docs/source/applications.rst
docs/source/multi-d-acq-tutorial.ipynb
pycromanager/acquire.py
pycromanager/test/test_MDA_events.py
pyproject.toml
setup.py

Closes: https://github.com/micro-manager/pycro-manager/issues/153
This should maintain all the previous behaviors but also allow for specifying z positions in these new ways:
- z_positions as 2D array
- z_positions as 1D array
- z_positions as 1D array + relative positions
which is hopefully made clear in the new docs page I added for this. 
Stuff like this is a great candidate for pytest, I thought about adding that but didn't becuase you already have a large user automated testing DIR that I wasn't sure would work with pytest on CI. Let me know what would be best

Allow relative z in multi_d_acquisition_events

---

.github/workflows/publish.yml

As the title says. This lets you create a git tag, build the wheel, and upload it to pypi in a few clicks via the github interface which I find to be convenient. 
This would require you to create a pypi api token:
then you would go to the github releases zone:
draft a new release:
then add whatever text you want and it will run the github action in this PR that builds the wheel and pushes it to pypi.
(this was totally unsolicited so no hard feelings if you close this)

add github action to publish to pypi

---

.github/workflows/publish.yml

follow up to https://github.com/micro-manager/pycro-manager/pull/170
On a push to `_version.py` on the master branch the action will trigger and do two things:
1. publish to pypi
2. push a tag to the repo

auto publish on push to _version.py

---

.github/workflows/publish.yml

so the action doesn't need to have numpy + dask etc... installed to extract the version for the git tag

don't require full install dependncies for publish action

---

pycromanager/utility/PropertyMap.py
pycromanager/utility/__init__.py
pycromanager/utility/examples/positionTransformation.py
pycromanager/utility/positions.py

This PR introduces utility code which I have been using for a while but which might make sense to have in this package.
This file contains Python classes which mirror the `PropertyMap`, and `Property` classes used in MMStudio.
`PropertyMap.loadFromFile()` enables users to load a property map saved to JSON by MMStudio
This file contains Python classes which mirror the `PositionList`, `MultiStagePosition`, etc. classes of MMStudio. See `examples/positionTransformation.py` for an example of using the `PositionList` to load a set of position list files, manipulating some of the positions in Python and then saving back to a file that can be loaded by MMStudio. 
This new `utility` subpackage would be a sensible place to store any other python code that is related to Micro-Manager but doesn't …

Add utility subpackage

---

java/src/main/java/org/micromanager/remote/RemoteEventSource.java
pycromanager/_version.py
pycromanager/acq_util.py
pycromanager/acquisitions.py
pycromanager/data.py
pycromanager/napari_util.py
pycromanager/zmq.py
requirements.txt
test/napari_frontend.py
test/napari_simple.py

This PR enables the use of napari as a frontend for pycro-manager acquisitions, either with the MM GUI running side by side, or independently from python using headless mode
FYI in case this is useful to you @dpshepherd @ptbrown1729 @AlexCoul
Example:
```python
from pycromanager import Acquisition, multi_d_acquisition_events, start_headless
import napari
acq = Acquisition(directory=r"C:\Users\henry\Desktop\data", name="test_acq",
show_display='napari')
events = multi_d_acquisition_events(num_time_points=8, time_interval_s=2,
z_start=0, z_end=6, z_step=0.7,)
acq.acquire(events)
acq.mark_finished()
napari.run()
```

Napari frontend for pycromanager

---

pycromanager/acq_util.py

1. Allow external cleaning up of subprocesses
2. return the core directly from start headless (nice convenience)

start_headless improvements

---

docs/source/calling_java.rst

I added the information about pymm-eventserver at the end of the file. I had to install pandoc on top of the procedure described in the contributing guidelines to make the build of the documentation work, but I think it should be fine.

Add information about pymm-eventserver

---

pycromanager/acq_util.py

micromanager driver that may appear before the STARTED token that indicates micromanager startup.

Added code to start_headless to skip over initial status messages from micromanager driver.

---

pycromanager/zmq_bridge/_bridge.py

Yesterday's [`numpy`'s 1.24.0 release](https://numpy.org/devdocs/release/1.24.0-notes.html#np-str0-and-similar-are-now-deprecated) deprecates `np.bool` which leads to the following error on a fresh installation:
```
>>> import pycromanager
/Users/talon.chandler/pycro-manager/pycromanager/zmq_bridge/_bridge.py:868: FutureWarning: In the future `np.bool` will be defined as the corresponding NumPy scalar.  (This may have returned Python scalars in past versions.
"boolean[]": np.bool,
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/Users/talon.chandler/pycro-manager/pycromanager/__init__.py", line 3, in <module>
from pycromanager.acquisitions import Acquisition, MagellanAcquisition, XYTiledAcquisition
File …
```

`np.bool` is deprecated in `numpy` 1.24.0

---

pycromanager/_version.py
pycromanager/acquisitions.py
pycromanager/test/test_acquisition.py

This PR add minimal acquisition events validation.
In the current implementation acquisition events need to be a dict or list of dict. Event dictionaries need to contain `axes` key. An exception is raised is supplied events are not valid. Requires ndtiff > 1.8.1
We can expand further from here.

Feature event validation

---

Contributing.md

fixes #608 
@henrypinkard let me know what you think about the simplification in the git instructions, we can easily revert these changes

Update Contributing.md with documentation on tests

---

pycromanager/test/test_acquisition.py

Otherwise, the viewer tests run with 1s exposure which makes them quite slow

Reset exposure time after tests for aborting sequenced acquisition

---

java/src/main/java/org/micromanager/lightsheet/StackResampler.java

- Rotation matrix rotated around x axis to yield results closer to reality (or so we think).
- Fix bug that caused null pointer exception when sending an image with null pixels (which was supposed to function as a termination signal).
- Bumped pom version to 0.41.7

Light sheet fixes

---

java/src/main/java/org/micromanager/lightsheet/StackResampler.java

Otherwise, strange ghost images appear when re-utilizing an instance of  this class.

StackResampler: clear queue when initializing projections.   

---

pycromanager/_version.py
pycromanager/zmq_bridge/bridge.py

supersedes https://github.com/micro-manager/pycro-manager/pull/740, which was breaking tests

Fix error on script end

---

java/pom.xml
pycromanager/_version.py
pycromanager/acq_future.py
pycromanager/acquisition/acq_eng_py/internal/engine.py
pycromanager/acquisition/acq_eng_py/main/AcqEngPy_Acquisition.py
pycromanager/acquisition/acq_eng_py/main/acq_notification.py

I have no way of actually running or testing this code.  Pycharm seems to think it will compile, except for the use of StrVector, which was not introduced by me.  This is an effort to play by the rules, but I have to say that the bar of contributing to AcqEngJ is pretty high given the requirement to write the same code in two languages and test in two completely different environments.

Added Before_Z_Hooks copy of AcqEngJ code.

---

pycromanager/logging.py

As described in #766, we should avoid tampering with the `root` logger object.
Happy to set the `"pycromanager"` logger's level to `DEBUG` by default if that is desired, but that also seems not-very-canonical from an outsider's perspective!

Do not set the root logger's level to DEBUG

---

pycromanager/_version.py
pycromanager/acquisition/acq_eng_py/internal/engine.py
pycromanager/headless.py

**Issue** #808:
For Java backend (`python_backend=False`) the `stop_headless` method raises an `AttributeError`.
Fixed by adding a check if `Engine` singleton has been initialized before trying to stop it.

Bugfix: stop_headless raises AttributeError #808 
