micro-manager/pycro-manager

- pycromanager/acquire.py
- setup.py
Available in pycromanager 0.4.3
> Fix image processer bug for non-rectangular cameras

- pycromanager/__init__.py
- pycromanager/_version.py
- setup.py
This allows
```python
from pycromanager import __version__
print(__version__)
```
which is useful for bug reporting and such
> add __version__

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/documentation.md
- .github/ISSUE_TEMPLATE/enhancement.md
- .github/ISSUE_TEMPLATE/other.md
Adds 4 issue templates. These are almost a straight rip of the ones I use which are pretty close to the ones used by jupyterlab, ipywidgets and matplotlib (I went on a bit of a rampage adding feature request templates at one point...)
Closes: #152
> create issue templates

- docs/source/application_notebooks/PSF_viewer.ipynb
- docs/source/applications.rst
added jupyter notebook with psf viewer. added doc string to applications.rst
> psf_viewer tutorial

- pycromanager/acquire.py
- test/headless_demo.py
- auto finds JRE on windows
- more options on Mac OS
- add flags to sync behavior between this and MM headless app
> Headless mode improvements

- pycromanager/utility/positions.py
This PR:
- Fixes a few bugs due to incorrectly named variables
- adds support for addition and subtraction between two `PositionList`s
- Makes some minor improvements to docstrings and exceptions.
> Improvements to PositionList utility class

- pycromanager/_version.py
- pycromanager/zmq.py
Following our discussion : https://github.com/micro-manager/pycro-manager/issues/314#issuecomment-1044851594
> Enable Iterable objects to be returned as lists 

- pycromanager/acq_util.py
- pycromanager/bridge.py
not sure why it wasn't passsing thorugh before, but does now seem too
> Probabl fixes headless 

- pycromanager/acq_util.py
- pycromanager/acquisitions.py
- pycromanager/java_classes.py
Added timeout argument to any function that creates a bridge and pass this argument through so that non-default timeout values are used when specified.
> Add timeouts

- pycromanager/_version.py
- requirements.txt
- setup.py
- test/regular_tiff_read.py
Hopefully this fixes the documentation
> update ndtiff version

- java/pom.xml
- pycromanager/test/test_acquisition.py
> Adding tests for successful channel sequencing

- java/pom.xml
@henrypinkard this is what you mean, correct?
How do you decide between major and minor version updates?
> bump PycroManagerJava version

- java/pom.xml
- update_dependency.py
> Java version auto-update

- .github/workflows/Java_dependency_update.yml
- .github/workflows/maven_deploy_and_mm_update.yml
- build_automation/update_dependency.py
- build_automation/update_mm_ivy.py
- java/pom.xml
Created by Github action (https://github.com/micro-manager/pycro-manager/blob/dependency-update/.github/workflows/Java_dependency_update.yml)
> Java dependency auto-update

- .gitignore
- pycromanager/test/test_acquisition.py
This is also a test of the dependency auto-update feature
> Add acq timing test

- pycromanager/zmq_bridge/_bridge.py
Fixes: https://github.com/micro-manager/pycro-manager/issues/527
> Check if arg_java_type exists in dict

- pycromanager/test/test_viewer.py
This PR adds testing of pycromanager viewers for timelapse acquisitions
> add viewer timelapse testing

- docs/source/acq_events.rst
- docs/source/apis.rst
- java/pom.xml
- java/src/main/java/org/micromanager/explore/ExploreAcqUIAndStorage.java
- java/src/main/java/org/micromanager/explore/ExploreAcquisition.java
- java/src/main/java/org/micromanager/remote/PycroManagerCompatibleAcq.java
- java/src/main/java/org/micromanager/remote/PycroManagerCompatibleUI.java
- java/src/main/java/org/micromanager/remote/RemoteAcquisition.java
- java/src/main/java/org/micromanager/remote/RemoteViewerStorageAdapter.java
- java/src/main/java/org/micromanager/remote/XYTiledRemoteAcquisition.java
- pycromanager/_version.py
- pycromanager/acquisitions.py
- scripts/xy_tiling.py
Also add new Java interfaces to ensure pycromanager-compatible components have all required fuctions
> Make row/col special axes names instead of fields in acquisition event

- pycromanager/acq_util.py
- pycromanager/test/test_MDA_events.py
Based on the discussion in https://github.com/micro-manager/pycro-manager/issues/602#issue-1729633195
I'm assuming the documentation will be automatically updated in the next build.
> Modifications to allow custom time intervals in a timelapse

- pycromanager/test/test_acquisition.py
This PR adds tests that the exposure time is correctly set for event sequences, e.g. #622. Requires [AcqEngJ 0.28.2](https://github.com/micro-manager/AcqEngJ/pull/94)
> Add exposure time tests

- java/pom.xml
- java/src/main/java/org/micromanager/lightsheet/StackResampler.java
Reverts rotation matrix, 3D is hard.  Also now really bumps pom.xml to 0.4.7
> Lightsheetfix2

- java/pom.xml
- java/src/main/java/org/micromanager/remote/RemoteEventSource.java
- java/src/main/java/org/micromanager/remote/RemoteImageProcessor.java
- java/src/main/java/org/micromanager/remote/RemoteNotificationHandler.java
- java/src/main/java/org/micromanager/remote/RemoteStorageMonitor.java
- pycromanager/_version.py
- pycromanager/acquisitions.py
- pycromanager/test/test_hook_functions.py
- pycromanager/zmq_bridge/_bridge.py
https://github.com/micro-manager/pycro-manager/issues/654
Internals mostly complete, still need to figure out how to expose to the user
> recieve acquisition notifications

- docs/requirements.txt
- docs/source/apis.rst
- pycromanager/acq_future.py
- pycromanager/acquisition/acq_eng_py/main/acq_notification.py
- pycromanager/acquisition/acquisition_superclass.py
- pycromanager/acquisition/java_backend_acquisitions.py
- pycromanager/acquisition/python_backend_acquisitions.py
- scripts/python_backend.py
- fix some python backend bugs
- remove directory from python backend acq
- fix documentation of acquisition class
> Fix Acquisition docs and small fixes for python backend

- pycromanager/headless.py
> Adding check on empty config_file on Python headless

- pycromanager/acquisition/acq_future.py
- pycromanager/test/test_notifications_futures.py
* Bugfix for #799 
* Add test case for above
> Bugfix for metadata return in `AcquisitionFuture.await_image_saved`

- scripts/introspection.py
This adds a script with some examples of how to do basic micro-manager introspection using pycro-manager.
> Introspection examples script.

- pycromanager/acquisition/acq_eng_py/main/AcqEngPy_Acquisition.py
At least for me, this fixes a problem with the python_backend not working with acquisition hooks.
> BEFORE_Z_DRIVE -> BEFORE_Z_HOOK
